
# basic configuration
#
baseURL: "https://truemped.github.io"
title: "all things considered..."

languagecode: "en"
defaultcontentlanguage: "en"

paginate: 20
canonifyurls: true

pygmentsstyle: "monokai"
pygmentscodefences: true
pygmentscodefencesguesssyntax: true

theme: "hugo-coder"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
