
# basic configuration
#
baseURL: "https://truemped.github.io"
title: "all things considered..."

languagecode: "en"
defaultcontentlanguage: "en"

pagination.pagerSize: 20
canonifyurls: true

pygmentsstyle: "monokai"
pygmentscodefences: true
pygmentscodefencesguesssyntax: true

theme: "hugo-coder"

enableRobotsTXT: true
buildDrafts: true
buildFuture: true
buildExpired: false
