
en:
  languagename: "English"

  menu:
    main:

      - name: "About Me"
        weight: 1
        url: "/about/"

      - name: "Blog"
        weight: 2
        url: "/posts/"

      - name: "Ideas & Concepts"
        weight: 3
        url: "/ideas-concepts/"
