name: GitHub Pages

on:
  push:
    branches:
      - source  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          ref: 'source'
          submodules: 'recursive'
          fetch-depth: 0

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.139.3"
          extended: true

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo --environment=live

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          #   keep_files: true
          user_name: truemped
          user_email: truemped@gmail.com
          publish_branch: master
        #   cname: example.com
